### ISSUE TITLE
Create F@H FAQ Bot

### ISSUE THREAD

**Issue by anniexudan** [likamrat/foldingathome#12]
Create  F@A FAQ Bot

**Comment by anniexudan** [comment]
@likamrat  I am still not able to assign to myself. Could you assign this issue to me?

Thanks.

**Comment by likamrat** [comment]
Love it!!

**Comment by likamrat** [comment]
@anniexudan can you please add some details to the issue. Follow this template:
https://github.com/likamrat/foldingathome/issues/6

**Comment by anniexudan** [comment]
### Idea
Develop an F@H Bot

### Expected Behavior
Develop an F@H Bot which you can find the FAQ of this F@H project.

**Comment by anniexudan** [comment]
Created the bot and finished
