### ISSUE TITLE
Create an Ubuntu install guide.

### ISSUE THREAD

**Issue by chmitch** [likamrat/foldingathome#13]
We've got screenshots for Windows and Mac, it might be handy to have an Ubuntu install guide too.

**Comment by likamrat** [comment]
Great!

Do you want to take this? Also, can you please follow this Template?
https://github.com/likamrat/foldingathome/issues/6

**Comment by chmitch** [comment]
Sure.  I'll take it.

**Comment by chmitch** [comment]
Idea
Develop an install guide for F@H on Ubuntu.

Expected Behavior
Repository will include an install guide for users choosing to run F@H on Ubuntu installs.

**Comment by david-okeefe** [comment]
I can help with this too.  I can do the install for Ubuntu Server 18.04.
