### ISSUE TITLE
F@H client does not use discrete GPU when an integrated GPU is present

### ISSUE THREAD

**Issue by david-okeefe** [likamrat/foldingathome#19]
## Idea
Provide guidance on how to have the F@H client leverage a discrete GPU in Windows when an integrated GPU is present.

## Expected Behavior
The repository will include additional configuration guidance for leveraging discrete GPUs in Windows for devices containing both integrated and discrete GPUs.

**Comment by likamrat** [comment]
@david-okeefe  I like it. you are taking this?

**Comment by david-okeefe** [comment]
I just figured out how to do this today so I will take this one.
