### ISSUE TITLE
Create F@H SDK 

### ISSUE THREAD

**Issue by adgroc** [likamrat/foldingathome#25]
### Idea
Create a C# SDK that is published to nuget.org and can be consumed by client apps

### Expected Behavior
SDK will consume F@H api's published at [https://stats.foldingathome.org/api](https://stats.foldingathome.org/api)

**Comment by likamrat** [comment]
@adgroc This is a great idea! do you want to take it?

**Comment by adgroc** [comment]
@likamrat - Already on it! :smile: Do we need to add a license to the repo?

**Comment by likamrat** [comment]
@adgroc awesome. the team is working on the license part. @devanshidiaries is looking at that.

**Comment by adgroc** [comment]
@likamrat - just issued pr #26 for the sdk, not much to it yet, but it's a start 😃

**Comment by likamrat** [comment]
Work is tracked here #31
