### ISSUE TITLE
Additional details needed on Ubuntu Server setup.

### ISSUE THREAD

**Issue by chmitch** [likamrat/foldingathome#28]
I think the Ubuntu setup script could benefit from some additional details:

1. It's a good idea to stop the FAHClient prior to updating the config.xml file.  Use the command:  sudo /etc/init.d/FAHClient stop
2. For folks who may be accessing the server from many places it would be good to call out you can do this with 0/0 instead of a specific IP:
<allow value="127.0.0.1 0/0"/>
<web-allow value="127.0.0.1 0/0"/>
3. After you edit the config.xml run sudo /etc/init.d/FAHClient start to restart the process.
4. For folks unfamiliar with editing files in a linux CLI it might be handy to give some basic notes that You can do that with the following steps:
a. cd /etc/FAHClient
b. sudo nano config.xml
c. make necessary edits.
d. Ctrl x + Y to save

**Comment by likamrat** [comment]
@david-okeefe can you take a look?

**Comment by david-okeefe** [comment]
I will incorporate the feedback above.
